before_script:
  - export __BUILD_ENV_=production
  - npm install
  - cd front-end && npm install && cd ..

test:
  stage: test
  image: node:8.11.3
  script:
    - npm test

build:
  stage: build
  image: node:8.11.3
  service: docker
  script:
    - npm run build
    - docker --version
